config/routes.rb
Rails.application.routes.draw do
  root    'accounts#new'
  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  delete  '/logout',   to: 'sessions#destroy'
  get     '/signup',   to: 'users#new'
  post    '/signup',   to: 'users#create'
  get     '/wait',     to: 'static_pages#wait_room'
  get     '/contact',  to: 'static_pages#contact'
  get     '/nah',      to: 'static_pages#no'
  resources :users, only: [:edit, :update, :destroy]
  resources :accounts do
    resources :comments, except: [:show]
  end
  resources :rounds, only: [:show]
  get "*path", to: redirect('/')
end

app/models/comment.rb
class Comment < ApplicationRecord
  attr_accessor :comment_group
  belongs_to :account
  validates :text, length: { maximum: 120 }
end

app/controllers/comments_controller.rb
class CommentsController < SharedController

  def index
    @account = Account.find(params[:account_id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    @comments = @account.comments
  end

  def new
    @account = Account.find(params[:account_id])
    redirect_to account_path(@account) and return if @account.comments.count > 0
    @comment_group = []
    (@account.match_amount).times do
      @comment_group << @account.comments.new
    end
  end

  def create
    @account = Account.find(params[:account_id])
    redirect_to account_path(@account) and return if @account.comments.count > 0

    over_length = false
    comment_params[:comment_group].each do |comment_hash|
      @account.comments.create(comment_hash)
      if comment_hash[:text].length > 120
        over_length = true
        @account.comments.create({text: ""})
      end
    end

    flash[:notice] = "Removed comment(s) exceeded the 120 character limit." if over_length
    redirect_to account_url(@account)
  end

  def edit
    @account = Account.find(params[:account_id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    @comment_group = []
    @account.comments.each { |comment| @comment_group << comment }
  end

  def update
    @account = Account.find(params[:account_id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    comment_params[:comment_group].each do |comment_hash|
      comment = @account.comments.find(comment_hash[0])
      comment.update_attributes(comment_hash[1])
    end
    redirect_to account_url(@account)
  end

  def destroy
    @account = Account.find(params[:account_id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    @comment = @account.comments.find(params[:id])
    @comment.destroy
    redirect_to account_url(@account)
  end

  private

    def comment_params
      params.permit(comment_group: [:text])
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div>
  <%= comment.text %>
</div>

<!-- <div>
  <%= link_to 'Destroy Comment', [comment.account, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</div> -->

app/views/comments/_form.html.erb
<%= form_tag account_comments_path do %>
  <% @comment_group.each_with_index do |comment, i| %>
    <%= fields_for 'comment_group[]', comment do |p| %>
      <div class="field">
        <%= i + 1 %>.
        <%= p.text_field :text, autofocus: true %>
      </div>

    <% end %>
  <% end %>
  <%= link_to 'Restart', account_path(@account), method: :delete, id: "leave-round"%>
  <div class="actions on-side">
    <%= submit_tag "Join Round" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= form_tag account_comment_path, method: :put do %>
  <% @comment_group.each_with_index do |comment, i| %>
    <%= fields_for 'comment_group[]', comment do |p| %>
      <div class="field">
        <%= i + 1 %>.
        <%= p.text_field :text, autofocus: true %>
      </div>

    <% end %>
  <% end %>

  <%= link_to 'Back', account_path(@account), id: "leave-round"%>

  <div class="actions on-side">
    <%= submit_tag "Update" %>
  </div>
<% end %>

app/views/comments/index.html.erb
<div class="comments-index-contain">
  <% @comments.each do |comment| %>
    <div style="margin-bottom:5px;">
      <%= comment.text %>
      <%= link_to 'Edit', edit_account_comment_path(@account, comment) %>
      <%= link_to 'Delete', account_comment_path(@account, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>

  <%= link_to 'Back', account_path(@account), id: "leave-round"%>  
</div>

app/views/comments/new.html.erb
<% provide(:title, "Account") %>

<div class="page-wrapper comment-container">
  <div class="box-heading">
    <p>Step 2 of 2 (optional)</p>
  </div>

    <h3 class="page-heading">Suggest <%= 'Comment'.pluralize(@account.match_amount) %></h3>

    <%= render 'comments/form' %>
</div>