config/routes.rb
Rails.application.routes.draw do
  root    'accounts#new'
  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  delete  '/logout',   to: 'sessions#destroy'
  get     '/signup',   to: 'users#new'
  post    '/signup',   to: 'users#create'
  get     '/wait',     to: 'static_pages#wait_room'
  get     '/contact',  to: 'static_pages#contact'
  get     '/nah',      to: 'static_pages#no'
  resources :users, only: [:edit, :update, :destroy]
  resources :accounts do
    resources :comments, except: [:show]
  end
  resources :rounds, only: [:show]
  get "*path", to: redirect('/')
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; 2018
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
<!-- <%= debug(params) if Rails.env.development? %> -->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="header-container">
    <div id="logo">
      Together
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_in_round? %>
          <li><%= link_to "Home", root_path %></li>
        <% else %>
          <li><%= link_to "Show", account_path(current_account) %></li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%= render 'layouts/rails_default' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>
  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>

      <div id="logo-under">
        Together
      </div>

      <div class="content">

        <div class="main">
          <div class="left-absolute">
            <div id="counter"></div>
          </div>
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <%= yield %>
        </div>

        <%= javascript_pack_tag 'timer' %>

        <div id="round-id" style="display:none">
          <%= current_round.id %>
        </div>

      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>