config/routes.rb
Rails.application.routes.draw do
  root    'accounts#new'
  get     '/login',    to: 'sessions#new'
  post    '/login',    to: 'sessions#create'
  delete  '/logout',   to: 'sessions#destroy'
  get     '/signup',   to: 'users#new'
  post    '/signup',   to: 'users#create'
  get     '/wait',     to: 'static_pages#wait_room'
  get     '/contact',  to: 'static_pages#contact'
  get     '/nah',      to: 'static_pages#no'
  resources :users, only: [:edit, :update, :destroy]
  resources :accounts do
    resources :comments, except: [:show]
  end
  resources :rounds, only: [:show]
  get "*path", to: redirect('/')
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  belongs_to :round
  has_many :comments, dependent: :destroy
  validates :username, :match_amount, presence: true
  validates :username, length: { maximum: 30 }
  before_save :set_get_amount

  private
    def set_get_amount
      self.get_amount = match_amount
    end
end

app/controllers/accounts_controller.rb
class AccountsController < SharedController
  def index
    redirect_to nah_path unless current_user.admin?
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user = current_user
    @account.round = Round.last
    unless @account.round.include_user?(current_user.id)
      if @account.save
        redirect_to new_account_comment_url(@account)
      else
        render :new
      end
    else
      redirect_to account_url(@account.round.find_user_account(current_user.id)),
      alert: 'You already have a round entry'
    end
  end

  def show
    @account = Account.find(params[:id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    if Round.last != @account.round
      redirect_to new_account_path
    end
  end

  def edit
    @account = Account.find(params[:id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
  end

  def update
    @account = Account.find(params[:id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    if @account.update(params[:account].permit(:username))
      redirect_to account_url
    else
      render 'edit'
    end
  end

  def destroy
    @account = Account.find(params[:id])
    redirect_to nah_path and return unless authorized? || current_user.admin?
    @account.destroy

    redirect_to root_path, alert: 'You have been romoved from the round'
  end

  private

    def account_params
      params.require(:account).permit(:username, :match_amount)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
  def current_account
    current_user.accounts.last
  end

  def authorized?
    return false unless current_account
    current_account.user == current_user
  end
end

app/views/accounts/_form.html.erb
<%= form_with model: @account, local: true do |f| %>

  <% if @account.errors %>
    <div id="error_explanation">
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :username, autofocus: true, placeholder: 'Username' %>
  </div>

  <div class="field">
    <%= f.select :match_amount, [ 5 ], prompt: 'Karma' %>
  </div>

  <div class="actions">
    <%= f.submit "Next" %>
  </div>

<% end %>

app/views/accounts/edit.html.erb
<%= form_with model: @account, local: true do |f| %>

  <% if @account.errors %>
    <div id="error_explanation">
      <ul>
        <% @account.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :username, placeholder: 'Username' %>
  </div>

  <%= link_to 'Back', account_path(@account), id: "leave-round"%>

  <div class="actions on-side">
    <%= f.submit "Save" %>
  </div>

<% end %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<table>
  <tr>
    <th>Account(#)</th>
    <th>Website</th>
    <th>Username</th>
    <th>Round(#)</th>
    <th colspan="2">Links</th>
  </tr>

  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.id %></td>
      <td><%= account.website %></td>
      <td><%= account.username %></td>
      <td><%= account.round.id %></td>
      <% if account.user == current_user || current_user.admin? %>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account_path(account),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/accounts/new.html.erb
<% provide(:title, "Account") %>

<div class="page-wrapper">
  <div class="box-heading">
    <p>Step 1 of 2</p>
  </div>

  <h3 class="page-heading">Enter Information</h3>

  <%= render 'form' %>

</div>

app/views/accounts/show.html.erb
<div id="wait-text">
  <i class="fa fa-users" aria-hidden="true"></i> You are entered
</div>

<div class="heading">
  Username <span><%= link_to 'Edit', edit_account_path %></span>
</div>

<div id="username"><%= @account.username %></div>

<% if @account.comments.count == 0 %>
  <%= link_to 'Add Comments', new_account_comment_path(@account, @account.comments) %>
<% end %>

<% if @account.comments.count > 0 %>
  <div class="heading">
    Comments
    <span>
      <%= link_to 'Edit', edit_account_comment_path(@account, 'current') %>
    </span>
  </div>
  <% count = 1 %>
  <% @account.comments.each do |comment| %>
    <% if comment.text != "" %>
      <div class="comment-text">
        <span><%= count %>.</span>
        <%= comment.text %>
      </div>
      <% count += 1 %>
    <% end %>
  <% end %>
<% end %>

<div class="leave-link">
  <%= link_to 'Leave Round', account_path, method: :delete, data: { confirm: 'Are you sure you wish to leave this round?' }, id: "leave-round"%>
</div>